### PR TITLE
implemented get waitlist endpoint for a shop owner

### PR DESCRIPTION
**Pull request by Ayomipo18**
image

### CODE REVIEW

**Review by Ikponwosae — CHANGES_REQUESTED** [review]
Can you return the count? 
waitlist.length

**Review by Ikponwosae — CHANGES_REQUESTED** [review]
there's no need for the auth and authorize here, they are passed in the app.js for all the shop owner routes

shopOwner get waitlist route

**Comment by Ayomipo18** [comment]
> Can you return the count? waitlist.length

done

**Comment by Ayomipo18** [comment]
> there's no need for the auth and authorize here, they are passed in the app.js for all the shop owner routes
> 
> shopOwner get waitlist route

done

**Review by Ikponwosae — APPROVED** [review]

**Pull request merged**
